name: Build

on:
  push:
    branches: [limine]
  pull_request:
    branches: [limine]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xorriso gcc g++ binutils make curl git

      - name: Build ISO
        run: make iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: moonshine.iso
          path: moonshine.iso
